// <auto-generated />
using System;
using EveDataStorage.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EveDataStorage.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20250424175513_State2")]
    partial class State2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("EveDataStorage.Models.Alliance", b =>
                {
                    b.Property<int>("AllianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("alliance_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AllianceId");

                    b.ToTable("Alliances");
                });

            modelBuilder.Entity("EveDataStorage.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("character_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EveDataStorage.Models.Corporation", b =>
                {
                    b.Property<int>("CorporationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("corporation_id");

                    b.Property<int?>("AllianceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CorporationId");

                    b.HasIndex("AllianceId");

                    b.ToTable("Corporations");
                });

            modelBuilder.Entity("EveDataStorage.Models.ItemPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AveragePrice")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("TEXT");

                    b.Property<double>("JitaBuyPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("JitaSellPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ItemPrices");
                });

            modelBuilder.Entity("EveDataStorage.Models.MiningObserver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<long>("ObserverId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MiningObservers");
                });

            modelBuilder.Entity("EveDataStorage.Models.ObservedMining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorporationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<long>("ObserverId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CorporationId");

                    b.ToTable("ObservedMinings");
                });

            modelBuilder.Entity("EveDataStorage.Models.CharacterMain", b =>
                {
                    b.HasBaseType("EveDataStorage.Models.Character");

                    b.Property<int?>("AllianceId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("AssociatedCharacterIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CorporationId")
                        .HasColumnType("INTEGER");

                    b.ToTable("CharacterMains");
                });

            modelBuilder.Entity("EveDataStorage.Models.Corporation", b =>
                {
                    b.HasOne("EveDataStorage.Models.Alliance", "Alliance")
                        .WithMany()
                        .HasForeignKey("AllianceId");

                    b.Navigation("Alliance");
                });

            modelBuilder.Entity("EveDataStorage.Models.ObservedMining", b =>
                {
                    b.HasOne("EveDataStorage.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EveDataStorage.Models.Corporation", "Corporation")
                        .WithMany()
                        .HasForeignKey("CorporationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Corporation");
                });

            modelBuilder.Entity("EveDataStorage.Models.CharacterMain", b =>
                {
                    b.HasOne("EveDataStorage.Models.Character", null)
                        .WithOne()
                        .HasForeignKey("EveDataStorage.Models.CharacterMain", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
