// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaticDataStorage.Contexts;

#nullable disable

namespace StaticDataStorage.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20260226112031_CelestialSde")]
    partial class CelestialSde
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("StaticDataStorage.Models.Blueprint", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CopyTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventionMaterialsStr")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("InventionMaterials");

                    b.Property<string>("InventionProductsStr")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("InventionProducts");

                    b.Property<int>("InventionTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManufacturingMaterialsStr")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ManufacturingMaterials");

                    b.Property<string>("ManufacturingProductsStr")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ManufacturingProducts");

                    b.Property<int>("ManufacturingTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxProductionLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReactionMaterialsStr")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ReactionMaterials");

                    b.Property<string>("ReactionProductsStr")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ReactionProducts");

                    b.Property<int>("ReactionTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResearchMaterialEfficientTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResearchTimeEfficientTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("Blueprints");
                });

            modelBuilder.Entity("StaticDataStorage.Models.Category", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IconID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("StaticDataStorage.Models.Celestial.Constellation", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SolarSystemIDs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WormholeClassID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("Constellations");
                });

            modelBuilder.Entity("StaticDataStorage.Models.Celestial.Moon", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrbitID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SolarSystemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("СelestialIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("Moons");
                });

            modelBuilder.Entity("StaticDataStorage.Models.Celestial.Planet", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSovResource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoonIDs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL");

                    b.Property<int>("SolarSystemID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SovResourceValue")
                        .HasColumnType("REAL");

                    b.Property<int>("TypeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("СelestialIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("StaticDataStorage.Models.Celestial.Region", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WormholeClassID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("StaticDataStorage.Models.Celestial.SolarSystem", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConstellationID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanetIDs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SecurityStatus")
                        .HasColumnType("REAL");

                    b.Property<int>("StarID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("SolarSystems");
                });

            modelBuilder.Entity("StaticDataStorage.Models.EntityType", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("BasePrice")
                        .HasColumnType("REAL");

                    b.Property<float>("Capacity")
                        .HasColumnType("REAL");

                    b.Property<int>("FactionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GraphicID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IconID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarketGroupID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Mass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetaGroupID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameRussian")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PortionSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Radius")
                        .HasColumnType("REAL");

                    b.Property<string>("SofFactionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SofMaterialSetID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoundID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VariationParentTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Key");

                    b.ToTable("EntityTypes");
                });

            modelBuilder.Entity("StaticDataStorage.Models.Group", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anchorable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anchored")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FittableNonSingleton")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IconID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseBasePrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("StaticDataStorage.Models.SdeVersionData", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("alliance_id")
                        .HasAnnotation("Relational:JsonPropertyName", "_key");

                    b.Property<int>("BuildNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("buildNumber")
                        .HasAnnotation("Relational:JsonPropertyName", "buildNumber");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("releaseDate")
                        .HasAnnotation("Relational:JsonPropertyName", "releaseDate");

                    b.HasKey("Key");

                    b.ToTable("SdeVersions");
                });

            modelBuilder.Entity("StaticDataStorage.Models.TypeMaterial", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialsStr")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("InventionMaterials");

                    b.HasKey("Key");

                    b.ToTable("TypeMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
